**Why to Use Numpy?**

-> It provides efficient storage
-> It provides better ways of handling data for processing
-> it is fast
-> Easy to learn
-> NumPy uses relative less memory to store data



In [2]:
import numpy as np #importing numpy library and taking it as np , one can take any variable like np , ro,h. 
#It helps to use numpy keyword as np



In [21]:
myarr = np.array([[3,6,8,9]],np.int8) #int8 signifies the size of integer

In [22]:
myarr

array([[3, 6, 8, 9]], dtype=int8)

In [23]:
myarr[0,2]

8

***Shape of the array***

In [24]:
myarr.shape

(1, 4)

***Type of the array***

In [10]:
myarr.dtype

dtype('int8')

***Changing existing element***

In [12]:
myarr[0,1] = 99

In [13]:
myarr[0,1]

99

In [33]:
roh = np.array([[1,2,3]],np.int32)

In [30]:
roh

array([[1, 2, 3]])

In [31]:
roh.shape

(1, 3)

In [34]:
roh.dtype

dtype('int32')

In [35]:
roh[0,2] = 55

In [36]:
roh

array([[ 1,  2, 55]], dtype=int32)

In [38]:
list = np.array([[1,2,3],[6,8,9],[7,4,6]])


In [39]:
list

array([[1, 2, 3],
       [6, 8, 9],
       [7, 4, 6]])

In [40]:
list.shape

(3, 3)

In [41]:
list.size

9

In [43]:
zero = np.zeros((2,5))

In [44]:
zero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [45]:
rng = np.arange(17)

In [46]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [50]:
lsp = np.linspace(1,50,10)

In [51]:
lsp

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [56]:
emp = np.empty((2,2),dtype = int)

In [57]:
emp

array([[    48557744,            0],
       [          64, 472446402592]])

In [60]:
emp_like = np.empty_like(lsp)

In [61]:
emp_like

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [58]:
fl = np.full((6,6),77)

In [59]:
fl

array([[77, 77, 77, 77, 77, 77],
       [77, 77, 77, 77, 77, 77],
       [77, 77, 77, 77, 77, 77],
       [77, 77, 77, 77, 77, 77],
       [77, 77, 77, 77, 77, 77],
       [77, 77, 77, 77, 77, 77]])

In [65]:
ide = np.identity((65))

In [66]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [67]:
arr = np.arange(99)

In [68]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [69]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [70]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [71]:
arr.shape

(99,)

In [105]:
x = [[1,2,3,4],[6,7,8,9]]

In [106]:
ar = np.array((x),dtype=object)

In [107]:
ar

array([[1, 2, 3, 4],
       [6, 7, 8, 9]], dtype=object)

In [108]:
ar.sum(axis=0)

array([7, 9, 11, 13], dtype=object)

In [109]:
ar.sum(axis =1)

array([10, 30], dtype=object)

In [110]:
ar.T

array([[1, 6],
       [2, 7],
       [3, 8],
       [4, 9]], dtype=object)

In [111]:
ar.flat

In [112]:
for item in ar.flat:
    print(item)

1
2
3
4
6
7
8
9


In [113]:
ar.ndim

2

In [114]:
ar.size

8

In [116]:
ar.nbytes

64

In [117]:
one = np.array([1,2,3,4,5])

In [118]:
one.argmax()

4

In [119]:
one.argmin()

0

In [120]:
ar.argsort()

array([[0, 1, 2, 3],
       [0, 1, 2, 3]])

In [121]:
one.argsort()

array([0, 1, 2, 3, 4])

In [126]:
one.sort()

In [127]:
one

array([1, 2, 3, 4, 5])

In [128]:
ar.sort()

In [129]:
ar

array([[1, 2, 3, 4],
       [6, 7, 8, 9]], dtype=object)

In [132]:
ar.ravel()

array([1, 2, 3, 4, 6, 7, 8, 9], dtype=object)

In [135]:
np.sqrt(one)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [137]:
one.sum()

15

In [139]:
np.where(one>3)

(array([3, 4]),)

In [140]:
type(np.where(one>3))

tuple

In [141]:
np.count_nonzero(one)

5

In [143]:
import sys

In [144]:
ch = [0,3,4,5]

In [145]:
chr = np.array(ch)

In [146]:
sys.getsizeof(1)*len(ch)

112

In [147]:
chr.itemsize*chr.size

32